# Generated by Django 4.2.2 on 2023-11-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='mail',
            field=models.EmailField(default='abc@gmail.com', max_length=254),
        ),
    ]
