# Generated by Django 4.2.2 on 2023-11-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employees_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='phone',
            field=models.IntegerField(default='234234234'),
        ),
    ]
