# Generated by Django 4.2.2 on 2023-11-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
